repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
     -  id: mypy
        files: sklearn/
        additional_dependencies: [pytest==6.2.4]
-   repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.14.0
    hooks:
    -   id: cython-lint
        args: [--max-line-length=999, --ignore=E24,E203,E731,E741,W503,W504]
