# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # This environment tests the latest available dependencies.
    # It runs tests requiring pandas and PyAMG.
    # It also runs with the site joblib instead of the vendored copy of joblib.
    - env: DISTRIB="conda" PYTHON_VERSION="*" INSTALL_MKL="true"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           CYTHON_VERSION="*" PYAMG_VERSION="*" PILLOW_VERSION="*"
           JOBLIB_VERSION="*" COVERAGE=true
           CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true"
           SKLEARN_SITE_JOBLIB=1 CHECK_WARNINGS="true"
      if: type != cron
    # This environment tests scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.6
       env: DISTRIB="scipy-dev" CHECK_WARNINGS="true"
       if: type = cron OR commit_message =~ /\[scipy-dev\]/

install: source build_tools/travis/install.sh
script: 
  - bash build_tools/travis/test_script.sh
  - bash build_tools/travis/test_docs.sh
  - bash build_tools/travis/test_pytest_soft_dependency.sh
after_success: source build_tools/travis/after_success.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
