language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - ENV="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    - ENV="conda" PYTHON_VERSION="2.6" COVERAGE="false"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
    - ENV="conda" PYTHON_VERSION="3.3" COVERAGE="false"
      NUMPY_VERSION="1.8.1" SCIPY_VERSION="0.13.3"
before_install: source travis/before_install.sh
install:
    - pip install coverage
    - if [[ "$COVERAGE" -eq "true" ]]; then pip install coveralls; fi
script: bash travis/test_script.sh
after_success:
    - if [[ "$COVERAGE" -eq "true" ]]; then coveralls; fi
cache: apt
