# Adapted from https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml
schedules:
- cron: "30 2 * * *"
  displayName: Run nightly build
  branches:
    include:
    - master
  always: true

jobs:
- job: linting
  displayName: Linting
  pool:
    vmImage: ubuntu-18.04
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - bash: |
        pip install flake8 mypy==0.780
      displayName: Install linters
    - bash: |
        set -ex
        if [[ $BUILD_REASON == "PullRequest" ]]; then
          # By default pull requests use refs/pull/PULL_ID/merge as the source branch
          # which has a "Merge ID into ID" as a commit message. The latest commit
          # message is the second to last commit
          COMMIT_ID=$(echo $BUILD_SOURCEVERSIONMESSAGE | awk '{print $2}')
          COMMIT_MESSAGE=$(git log $COMMIT_ID -1 --pretty=%B)
        else
          COMMIT_MESSAGE=$BUILD_SOURCEVERSIONMESSAGE
        fi
        echo "##vso[task.setvariable variable=COMMIT_MESSAGE]$COMMIT_MESSAGE"
      displayName: Get source version message
    - bash: |
        set -ex
        if [[ "$COMMIT_MESSAGE" =~ "[lint skip]" ]]; then
          # skip linting
          echo "Skipping flake8 linting"
          exit 0
        else
          ./build_tools/circle/linting.sh
        fi
      displayName: Run linting
    - bash: |
        set -ex
        if [[ "$COMMIT_MESSAGE" =~ "[lint skip]" ]]; then
          # skip linting
          echo "Skipping mypy linting"
          exit 0
        else
          mypy sklearn/ --ignore-missing-imports
        fi
      displayName: Run mypy
    - bash: |
        if [[ "$COMMIT_MESSAGE" =~ "[scipy-dev]" ]] || [[ $BUILD_REASON == "Schedule" ]]; then
          echo "Running scipy-dev"
          echo "##vso[task.setvariable variable=runScipyDev;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=runScipyDev;isOutput=true]false"
        fi
      name: gitCommitMessage
      displayName: Determine to run scipy-dev
