[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools<60.0",
    "wheel",
    "Cython>=0.28.5",

    # use oldest-supported-numpy which provides the oldest numpy version with
    # wheels on PyPI
    #
    # see: https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
    "oldest-supported-numpy",

    # nightly scipy 1.10.0.dev0 are the first wheels available for python 3.11
    "scipy==1.10.0.dev0; python_version>='3.11'",
    "scipy>=1.3.2",
]

[tool.black]
line-length = 88
target_version = ['py38', 'py39', 'py310']
preview = true
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.mypy_cache
  | \.vscode
  | build
  | dist
  | doc/tutorial
  | doc/_build
  | doc/auto_examples
  | sklearn/externals
  | asv_benchmarks/env
)/
'''
