[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "Cython>=0.28.5",
    "numpy>=1.11.0",
    "scipy>=0.17.0",
    "joblib>=0.11",
]
