parameters:
  name: ''
  vmImage: ''
  matrix: []
  dependsOn: []
  dependsOnParallel: []
  condition: ''
  commitMessage: ''

jobs:

# When [azure parallel] is *not* in the commit message, sequential runs 
# are performed via this jobs' template parametrisation.
# Later runs should check if the first run succeeded or skipped by using:
# in(dependencies[{{ parameters.name }}]['result'], 'Succeeded', 'Skipped')
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: |
      and(
        ${{ parameters.condition }},
        not(contains(${{ parameters.commitMessage }}, '[azure parallel]'))
      )

# When [azure parallel] is in the commit message, parallel runs are
# performed via this jobs' template parametrisation.
# The job on top is skipped so later jobs can be run in parallel
# with this jobs' template parametrisation.
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}_Parallel
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOnParallel }}
    condition: |
      and(
        ${{ parameters.condition }},
        contains(${{ parameters.commitMessage }}, '[azure parallel]')
      )
