parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    TEST_DIR: "/tmp/sklearn"
    VIRTUALENV: "testvenv"
    JUNITXML: "test-data.xml"
    OMP_NUM_THREADS: "4"
    OPENBLAS_NUM_THREADS: "4"
  strategy:
    matrix:
      ${{ if eq(parameters.name, 'macOS') }}:
        pylatest_conda:
          DISTRIB: "conda"
          PYTHON_VERSION: "*"
          INSTALL_MKL: "true"
          NUMPY_VERSION: "*"
          SCIPY_VERSION: "*"
          CYTHON_VERSION: "*"
          PILLOW_VERSION: "*"
          JOBLIB_VERSION: "*"
          CONVERAGE: "true"
      ${{ if eq(parameters.name, 'Linux') }}:
        # Linux environment to test that scikit-learn can be built against
        # versions of numpy, scipy with ATLAS that comes with Ubuntu Xenial 16.04
        # i.e. numpy 1.11 and scipy 0.17
        py35_np_atlas:
          DISTRIB: "ubuntu"
          PYTHON_VERSION: "3.5"
          SKLEARN_SITE_JOBLIB: "1"
          JOBLIB_VERSION: "0.11"
      # Linux + Python 3.5 build with OpenBLAS and without SITE_JOBLIB
        py35_conda_openblas:
          DISTRIB: "conda"
          PYTHON_VERSION: "3.5"
          INSTALL_MKL: "false"
          NUMPY_VERSION: "1.11.0"
          SCIPY_VERSION: "0.17.0"
          CYTHON_VERSION: "*"
          PILLOW_VERSION: "4.0.0"
          CONVERAGE: "true"
          SKLEARN_SITE_JOBLIB: "1"
      # Linux environment to test the latest available dependencies and MKL.
      # It runs tests requiring pandas and PyAMG.
      # It also runs with the site joblib instead of the vendored copy of joblib.
        pylatest_conda:
          DISTRIB: "conda"
          PYTHON_VERSION: "*"
          INSTALL_MKL: "true"
          NUMPY_VERSION: "*"
          SCIPY_VERSION: "*"
          PANDAS_VERSION: "*"
          CYTHON_VERSION: "*"
          PYAMG_VERSION: "*"
          PILLOW_VERSION: "*"
          JOBLIB_VERSION: "*"
          CONVERAGE: "true"
          CHECK_PYTEST_SOFT_DEPENDENCY: "true"
          TEST_DOCSTRINGS: "true"
          SKLEARN_SITE_JOBLIB: "1"
          CHECK_WARNINGS: "true"

  steps:
    - script: |
        build_tools/azure/install.sh
      displayName: 'Install'
    - script: |
        build_tools/azure/test_script.sh
      displayName: 'Test library'
    - script: |
        build_tools/azure/test_docs.sh
      displayName: 'Test docs'
    - script: |
        build_tools/azure/test_pytest_soft_dependency.sh
      displayName: 'Test soft dependency'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: ${{ '$(TEST_DIR)/$(JUNITXML)' }}
        testRunTitle: ${{ format('{0}-$(DISTRIB)-$(PYTHON_VERSION)', parameters.name) }}
