parameters:
  name: ''
  vmImage: ''
  matrix: []
  dependsOn: []
  dependsOnParallel: []
  condition: ''
  parallelCondition: ''

jobs:
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: |
      and(
        ${{ parameters.condition }},
        not(${{ parameters.parallelCondition }})
      )

- template: posix.yml
  parameters:
    name: ${{ parameters.name }}_Parallel
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOnParallel }}
    condition: |
      and(
        ${{ parameters.condition }},
        ${{ parameters.parallelCondition }}
      )
