parameters:
  name: ''
  vmImage: ''


jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    TEST_DIR: "/tmp/sklearn"
    VIRTUALENV: "testvenv"
  strategy:
    matrix:
      ${{ if eq(parameters.name, 'Linux') }}:
        # Linux environment to test that scikit-learn can be built against
        # versions of numpy, scipy with ATLAS that comes with Ubuntu Xenial 16.04
        # i.e. numpy 1.11 and scipy 0.17
        # py35_np_111:
        #   DISTRIB: "ubuntu"
        #   PYTHON_VERSION: "3.5"
        #   SKLEARN_SITE_JOBLIB: "1"
        #   JOBLIB_VERSION: "0.11"
        # Linux + Python 3.5 build with OpenBLAS and without SITE_JOBLIB
        py35_conda:
          DISTRIB: "conda"
          PYTHON_VERSION: "3.5"
          NUMPY_VERSION: "1.11.0"
          SCIPY_VERSION: "0.17.0"
          PILLOW_VERSION: "4.0.0"
          SKLEARN_SITE_JOBLIB: "1"
          INSTALL_MKL: "false"

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
        architecture: 'x64'
    - script: |
        build_tools/azure/install.sh
      displayName: 'Install'
    - script: |
        build_tools/azure/test_script.sh
      displayName: 'Test library'
    - script: |
        build_tools/azure/test_docs.sh
      displayName: 'Test docs'
    - script: |
        build_tools/azure/test_pytest_soft_dependency.sh
      displayName: 'Test soft dependency'
