parameters:
  name: ''
  vmImage: ''
  # matrix: []
  dependsOn: []
  condition: ''

jobs:
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}
    vmImage: ${{ parameters.vmImage }}
    # matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${ parameters.condition }}
