parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    TEST_DIR: '/tmp/sklearn'
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    OMP_NUM_THREADS: '4'
    OPENBLAS_NUM_THREADS: '4'
    SKLEARN_SKIP_NETWORK_TESTS: '1'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        build_tools/azure/install.sh
      displayName: 'Install'
    - script: |
        build_tools/azure/test_script.sh
      displayName: 'Test library'
    - script: |
        build_tools/azure/test_docs.sh
      displayName: 'Test docs'
    - script: |
        build_tools/azure/test_pytest_soft_dependency.sh
      displayName: 'Test soft dependency'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: ${{ '$(TEST_DIR)/$(JUNITXML)' }}
        testRunTitle: ${{ format('{0}-$(DISTRIB)-$(PYTHON_VERSION)', parameters.name) }}
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
    - script: |
        build_tools/azure/upload_codecov.sh
      condition: and(succeeded(), eq(variables['COVERAGE'], 'true'), eq(variables['DISTRIB'], 'conda'))
      failOnStderr: false
