parameters:
  name: ''
  vmImage: ''
  matrix: []
  dependsOn: []
  dependsOnParallel: []
  condition: ''

jobs:
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: |
      and(
        ${{ parameters.condition }},
        not(contains(dependencies['git_commit']['outputs']['commit.message'], '[azure all-parallel]'))
      )

- template: posix.yml
  parameters:
    name: ${{ parameters.name }}_Parallel
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOnParallel }}
    condition: |
      and(
        ${{ parameters.condition }},
        contains(dependencies['git_commit']['outputs']['commit.message'], '[azure all-parallel]')
      )
