channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.17.3
  - blas=*=openblas
  - scipy=1.3.2
  - cython
  - joblib
  - threadpoolctl=2.2.0
  - pandas
  - matplotlib=3.1.2
  - pyamg
  - pillow
  - pytest=6.2.5
  - pytest-xdist
  - codecov
  - pytest-cov
  - coverage=6.2
  - ccache
