channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - blas[build=openblas]
  - scipy
  - cython
  - joblib
  - threadpoolctl
  - matplotlib
  - pandas
  - pyamg
  - pytest=6.2.5
  - pytest-xdist
  - pillow
  - ccache
