channels:
  - defaults
dependencies:
  - python
  - numpy
  - blas[build=mkl]
  - scipy
  - cython
  - joblib
  - threadpoolctl
  - matplotlib
  - pandas
  - pyamg
  - pytest=6.2.5
  - pytest-xdist
  - pillow
  - codecov
  - pytest-cov
  - coverage=6.2
  - ccache
