
parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    VIRTUALENV: "testvenv"
  strategy:
    matrix:
      CONDA_PY: "37"

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''
    - script: |
        build_tools\\azure\\install.cmd
      display: 'Install'
