
name: Assign
on:
  issue_comment:
    types: created

jobs:
  one:
    runs-on: ubuntu-latest
    # Support m
    # toJson(github.event.comment.body) allows newline to be detected
    # if: >-
    #   (github.event.comment.body == 'take' ||
    #    github.event.comment.body == 'take ' ||
    #    github.event.comment.body == 'take\nwow' )
    #    && !github.event.issue.assignee
    steps:
      - run: echo "1"
        if: github.event.comment.body == 'take\n'
      - run: echo "2"
        if: github.event.comment.body == 'take\\n'
      - run: echo "3"
        if: github.event.comment.body == 'take\\\n'
      - run: echo "4"
        if: github.event.comment.body == 'take\\\n'
