# This action is triggered when the linter (lint.yml) workflow is completed.
# It will download the artifact (the lint log) from that job, parse it,
# and create a comment based on it.
# This is done this way so that the action has permissions to write comments
# on PRs.
name: Comment on failed linting

on:
  workflow_run:
    workflows: ["linter"]
    types:
      - completed

jobs:
  get-pr-number:
    # using a separate job for this action to limit the permissions of the
    # GITHUB_TOKEN to only read pull requests.
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
    steps:
      # This step is needed to get the pull request number used the last step
      # under the name: `needs.get-pr-number.outputs.pullRequestNumber`.
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_5
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

  comment:
    needs: get-pr-number
    runs-on: ubuntu-latest
    permissions:
      # Setting permissions for GITHUB_TOKEN to write comments on PRs.
      # The process-comments step needs to delete and add comments to the PR
      # which is exposed under the issues endpoint.
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install requests

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: lint-log

      - name: Show Logs
        id: show-logs
        run: cat linting_output.txt

      - name: Process Comments
        id: process-comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ needs.get-pr-number.outputs.pullRequestNumber }}
        run: python ./build_tools/get_comment.py
