name: Check Changelog
# This check makes sure that the changelog is properly updated
# when a PR introduces a change in a test file.
# To bypass this check, label the PR with  no-changelog.
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') == 0 }}
    steps:
      - name: Get PR number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Check the changelog only if tests have been modified
        run: |
          set -xe
          tests=$(git diff --name-only origin/master)
          if [[ "$tests" =~ tests ]]
          then
            result=$(cat ./doc/whats_new/v*.rst)
            if [[ "$result" =~ :pr:\`$PR_NUMBER\` ]]
            then
              echo "Changelog has been updated."
            else
              echo "Changelog entry is missing. If no changelog entry is required for this PR, label the PR with no-changelog to bypass this check."
              exit 1
            fi
          fi
