name: Check Changelog
# This check makes sure that the changelog is properly updated
# when a PR introduces a change in a test file.
# To bypass this check, label the PR with "No Changelog Needed".
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(contains(github.event.pull_request.labels.*.name, 'No Changelog Needed') == 0 }}
    steps:
      - name: Get PR number and milestone
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "MILESTONE_TITLE=${{ github.event.pull_request.milestone.title }} >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Check the changelog only if tests have been modified
        run: |
          set -xe
          tests=$(git diff --name-only origin/master)
          if [[ "$tests" =~ tests ]]
          then
            result=$(cat ./doc/whats_new/v*.rst)
            if [[ "$result" =~ :pr:\`$PR_NUMBER\` ]]
            then
              echo "Changelog has been updated."
              check_mlstn=$(cat ./doc/whats_new/v${MILESTONE_TITLE:0:4}.rst)
              if [[ "$check_mlstn" =~ :pr:\`$PR_NUMBER\` ]]
              then
                echo "Changelog and milestone correspond."
              else
                echo "Changelog and milestone do not correspond. Please move the changelog description or change the milestone."
                exit 1
              fi
            else
              echo "Changelog entry is missing. If no changelog entry is required for this PR, label the PR with 'No Changelog Needed' to bypass this check."
              exit 1
            fi
          fi
