name: CPython Nightly

on:
  schedule:
    # Nightly build at 1:00 A.M. on Sunday
    - cron: "0 1 * * 0"
  pull_request:
  # Manual run
  workflow_dispatch:

jobs:
  nightly:
    name: Nightly CPython-${{ matrix.python-version }}
    if: "github.repository == 'scikit-learn/scikit-learn' && contains(github.event.commits[0].message, '[python-dev]')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.10.0-alpha - 3.10.x'
            install-numpy: 'wheel'
            install-scipy: 'git'
    env:
      INSTALL_NUMPY: ${{ matrix.install-numpy }}
      INSTALL_SCIPY: ${{ matrix.install-scipy }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        run: |
          sudo apt-get install libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev libmpc-dev
          pip install --upgrade pip setuptools
      - name: Install python dependencies
        run: |
          pip install pytest pytest-xdist cython
      - name: Install numpy
        run: |
          if [[ $INSTALL_NUMPY == "wheel" ]]; then
            pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
          else
            pip install git+https://github.com/numpy/numpy.git
          fi
      - name: Install scipy
        run: |
          if [[ $INSTALL_SCIPY == "wheel" ]]; then
            pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
          else
            pip install git+https://github.com/scipy/scipy.git
          fi
      - name: Install scikit-learn
        run: |
          pip install --no-build-isolation .
      - name: Test scikit-learn
        run: |
          cd /tmp && python -m pytest -n 2 --pyargs sklearn
