name: CUDA GPU
on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: Test the contents of this Pull Request
        required: true

permissions: read-all

jobs:
  tests:
    runs-on: GPU
    name: Run Array API unit tests
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      # change this to checkout a particular PR if a PR number is provided as input
      - name: Checkout main repository
        uses: actions/checkout@v2
      - name: Checkout a particular Pull Request
        if: inputs.pr_id
        env:
          PR_ID: ${{ inputs.pr_id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Checking out" ${{ env.PR_ID }}
          gh pr checkout ${{ env.PR_ID }}
      - name: Cache conda environment
        id: cache-conda
        uses: actions/cache@v3
        env:
          # If you modify either of the "Install miniforge" or "Install dependencies" steps
          # below, bump the counter in `cache-name` to invalidate the cache
          cache-name: cache-conda-env-0
        with:
          path: ~/conda
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('build_tools/github/pylatest_conda_forge_cuda_array-api_linux-64_conda.lock') }}
      - name: Install miniforge
        if: ${{ steps.cache-conda.outputs.cache-hit != 'true' }}
        run: |
          curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3-$(uname)-$(uname -m).sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          rm Miniforge3-$(uname)-$(uname -m).sh
      - name: Install dependencies
        if: ${{ steps.cache-conda.outputs.cache-hit != 'true' }}
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          # defines the get_dep and show_installed_libraries functions
          source build_tools/shared.sh
          conda activate base
          # XXX switch once https://github.com/scikit-learn/scikit-learn/pull/29176 is merged
          conda install -c conda-forge "$(get_dep conda-lock min)" -y
          conda-lock install --name sklearn build_tools/github/pylatest_conda_forge_cuda_array-api_linux-64_conda.lock
      - name: Install scikit-learn
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate sklearn
          pip install --verbose --no-build-isolation --config-settings editable-verbose=true --editable .
      - name: Run array API tests
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate sklearn
          pytest -k 'array_api'
