# Workflow to build and publish the documentation
name: Documentation builder

on:
  schedule:
    # Nightly build at 3:42 A.M.
    - cron: "42 3 */1 * *"
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.X"
  # Manual run
  workflow_dispatch:

jobs:
  # Build the documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build documentation
        run: build_tools/circle/build_doc.sh
        env:
          OMP_NUM_THREADS: 2
          MKL_NUM_THREADS: 2
          NUMPY_VERSION: latest
          SCIPY_VERSION: latest
          MATPLOTLIB_VERSION: latest
          CYTHON_VERSION: latest
          SCIKIT_IMAGE_VERSION: latest
          SPHINX_VERSION: min
          PANDAS_VERSION: latest
          SPHINX_GALLERY_VERSION: latest
          NUMPYDOC_VERSION: latest
          SPHINX_PROMPT_VERSION: latest
          SPHINXEXT_OPENGRAPH_VERSION: latest

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: doc/_build/html/stable

  # Push the documentation
  push:
    runs-on: ubuntu-latest
    needs: [build]
    # if: github.event_name != 'pull_request'
    steps:
      - name: Download documentation
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      - name: Checkout scikit-learn
        uses: actions/checkout@v2
        with:
          path: scikit-learn

      - name: Checkout scikit-learn.github.io
        uses: actions/checkout@v2
        with:
          repository: scikit-learn/scikit-learn.github.io
          path: scikit-learn.github.io
          # ssh-key: ${{ secrets.SKLEARN_CI_SSH_KEY }}

      - name: Push documentation
        run: scikit-learn/build_tools/circle/push_doc.sh
