# Workflow to build and publish the documentation
name: Documentation builder

on:
  schedule:
    # Nightly build at 3:42 A.M.
    - cron: "42 3 */1 * *"
  # TODO: Remove when the pull request is ready to merge
  pull_request:
    branches:
      - main

jobs:
  # Build the documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build documentation
        run: build_tools/github/build_doc.sh
        env:
          OMP_NUM_THREADS: 2
          MKL_NUM_THREADS: 2
          CONDA_ENV_NAME: testenv
          NUMPY_VERSION: latest
          SCIPY_VERSION: latest
          MATPLOTLIB_VERSION: latest
          CYTHON_VERSION: latest
          SCIKIT_IMAGE_VERSION: latest
          # Bump the version from time to time because the
          # latest version tends to break things too often
          SPHINX_VERSION: 4.2.0
          PANDAS_VERSION: latest
          SPHINX_GALLERY_VERSION: latest
          NUMPYDOC_VERSION: latest
          SPHINX_PROMPT_VERSION: latest
          SPHINXEXT_OPENGRAPH_VERSION: latest

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: doc/_build/html/stable
