name: Pull Request Regex Title Labeler
on:
  pull_request_target:
    types: [opened, edited]

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read
  pull-requests: write

jobs:

  labeler:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.9'
    - name: Install PyGithub
      run: pip install -Uq PyGithub
    - name: Label pull request
      run: python .github/scripts/label_title_regex.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
