name: Labels Blank issues

on:
  issues:
    types: [opened]

jobs:
  label-blank-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # v1.0.4
        with:
          add-labels: "Needs Triage"
          ignore-if-labeled: true
