name: Publish to Pypi
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version upload to pypi'
        required: true
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'testpypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish_pypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -U wheelhouse_uploader pyyaml
    - name: Downloading wheels and sdist from staging
      env:
        SKLEARN_VERSION: ${{ github.event.inputs.version }}
      run: |
        echo "Download $SKLEARN_VERSION wheels and sdist"
        python -m wheelhouse_uploader fetch \
          --version $SKLEARN_VERSION \
          --local-folder dist/ \
          scikit-learn \
          https://pypi.anaconda.org/scikit-learn-wheels-staging/simple/scikit-learn/
    - name: Check dist has the correct number of artifacts
      run: |
        python build_tools/github/check_wheels.py
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
      with:
        repository-url: https://test.pypi.org/legacy/
        print-hash: true
      if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
      if: ${{ github.event.inputs.pypi_repo == 'pypi' }}
      with:
        print-hash: true
