# Workflow to trigger the jobs that will host the documentation
name: Documentation push trigger
on:
  workflow_run:
    # Run the workflow after the separate "Documentation builder" workflow completes
    workflows: [Documentation builder]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    # Run the job only if the "Documentation builder" workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        if: github.event.workflow_run.event == 'pull_request'
      - name: Install PyGithub
        run: pip install -Uq PyGithub
        if: github.event.workflow_run.event == 'pull_request'
      - name: Get PR number
        run: |
          PULL_REQUEST_NUMBER=$(python maint_tools/get_pr_number_from_run_id.py ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $RUN_ID)
          echo "PULL_REQUEST_NUMBER=$PULL_REQUEST_NUMBER" >> $GITHUB_ENV
        if: github.event.workflow_run.event == 'pull_request'
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
      - name: Trigger hosting jobs
        run: bash build_tools/github/trigger_hosting.sh
        env:
          CIRCLE_CI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}
          EVENT: ${{ github.event.workflow_run.event }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          PULL_REQUEST_NUMBER: ${{ env.PULL_REQUEST_NUMBER }}
