
name: Reviewed
# Runs when a review is submitted to a PR and
# remove the "Waiting for Reviewer" label
on:
  pull_request_review:
    types: submitted

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name:
        if: github.event.pull_request.state == 'open'
        run: |
          echo "Marking pull request ${{ github.event.pull_request.number }} as reviewed"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X "DELETE" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/Waiting%20for%20Reviewer
