
name: Reviewed
# Runs when a review is submitted to a PR and
# remove the "Waiting for Reviewer" label
on:
  pull_request_review:
    types: submitted

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/scikit-learn/teams/core-devs/members >> $CORE_DEV_ENV
          echo "${{ CORE_DEV_ENV.*.login }}"
      - name: Relabeling
        if: github.event.pull_request.state == 'open'
            && contains(${{ CORE_DEV_ENV.*.login }}, github.event.pull_request_review.sender)
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/scikit-learn/teams/core-devs/members >> $CORE_DEV_ENV
          if
          echo "Marking pull request ${{ github.event.pull_request.number }} as reviewed by"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X "DELETE" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/Waiting%20for%20Reviewer
