# Workflow to build and test wheels
name: Wheel builder

on:
  schedule:
    # Nightly build at 3:42 A.M.
    - cron: "42 3 */1 * *"
  push:
    tags:
      # Final releases, release candidates and post-releases build
      - "[0-9]+.[0-9]+.[0-9]+(rc[0-9]+)?(.post[0-9]+)?"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.X"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
    
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          # Build the wheels for Python 3.6 and newer
          CIBW_SKIP: pp* *p27* *p35*
          CIBW_TEST_REQUIRES: pytest pandas
          CIBW_TEST_COMMAND: pytest --pyargs sklearn
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          ls -l wheelhouse/*.whl

      - name: Store wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl 

  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      # The setup file requires these dependencies to be installed
      - name: Install dependencies
        run: |
          python -m pip install numpy scipy cython

      - name: Build source distribution
        run: |
          python setup.py sdist
          ls -l dist/*.tar.gz

      - name: Check source distribution
        run: |
          python -m pip install twine
          twine check dist/*.tar.gz

      - name: Install source distribution
        run: |
          pip install dist/*.tar.gz

      - name: Run tests
        run: |
          python -m pip install pytest pandas
          pytest --pyargs sklearn

      - name: Store source distribution
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]

    # The artifacts should not be uploaded on PRs
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Display artifacts
        run: |
          ls -l dist/*

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Upload artifacts
        env:
          # Secret variables need to mapped to environment variables explicitly
          SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
          SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_STAGING_UPLOAD_TOKEN }}
        # Force a replacement if the remote file already exists
        run: |
          if [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
            ANACONDA_ORG="scipy-wheels-nightly"
            ANACONDA_TOKEN="$SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN"
          else
            ANACONDA_ORG="scikit-learn-wheels-staging"
            ANACONDA_TOKEN="$SCIKIT_LEARN_STAGING_UPLOAD_TOKEN"
          fi
          conda install -q -y anaconda-client
          anaconda -t $ANACONDA_TOKEN upload --force -u $ANACONDA_ORG dist/*
